### ISSUE TITLE
No color in the circles under Sts column (Windows)

### ISSUE THREAD

**Issue by graphixillusion** [fujiapple852/trippy#1084]
As the title says i have no colored circles under the Sts column under Windows 11. I just have black and white circles filled with black lines

https://i.imgur.com/sAPZ4J4.png

**Comment by fujiapple852** [comment]
Hi @graphixillusion 

Can you confirm what terminal/shell you are using? i.e. `cmd.exe`, `PowerShell`, `Windows Terminal Preview`?

I assume `PowerShell` as that is how it appears for me as well.

The status circles are these Unicode values: 🔴 🟡 🟤 🔵 🟢

You will find lots of information online about how to get PowerShell to display unicode correctly (involves changing registry setting, modifying code pages, fonts) but as i'm not a regular Windows user I have not explored these.  

There easiest and more often recommended option is to simply switch to Windows Terminal Preview which displays Unicode correctly.  That is what I do when I test on Windows and it works without issue.

**Comment by graphixillusion** [comment]
Yep you are right. In Windows 11 when you run cmd.exe it will shows up in the Windows terminal, but if you run cmd as an admin it will just open a simple cmd.exe window will doesn't render the circles correctly. Tried again with a wt.exe as an admin and the circles are rendered correctly.
