### ISSUE TITLE
DestinationUnreachable incorrectly assumed to come from target host

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#1225]
Trippy currently assumes that ICMP DestinationUnreachable errors are from the target host, as can be seen from line 758 in the code below:

https://github.com/fujiapple852/trippy/blob/c5b9de07a252a9330893f85d42290d06b73d8a07/crates/trippy-core/src/strategy.rs#L742-L761

**Comment by c-git** [comment]
This also interacts with not crashing on errors from https://github.com/fujiapple852/trippy/issues/1238 because all nodes along the path get resolved to the local machine's host name.
