### ISSUE TITLE
Highlight lost probes in sample history

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#1247]
When a probe times out (does not respond before a round ends) or fails to send (due to a local network error) the samples chart shown it as the absence of a value (a blank vertical bar).  For example:

<img width="310" alt="Screenshot 2024-07-27 at 5 08 47 PM" src="https://github.com/user-attachments/assets/6ed25ba6-2ca6-41b4-827c-9dc13934fb63">

It is desirable to show `Awaited` (i.e. timed out) and `Failed` probes as solid vertical lines of different colours to make the distinction clearer.

**Comment by c-git** [comment]
Yeah I think that would be more intuitive when reading the chart and would make nodes that never responded have a full bar instead of an empty bar which might be better. I think a full bar is better but I guess that's subjective.

**Comment by fujiapple852** [comment]
I actually did this in an early version of Trippy (red vertical bar for 0), but I had to vendor and modify `tui-rs` (as it was then) in place.  I'll have to upstream the change to the widget.

**Comment by fujiapple852** [comment]
WIP:
<img width="435" alt="Screenshot 2024-08-14 at 6 33 17 PM" src="https://github.com/user-attachments/assets/43b3abf6-4964-4f85-97a6-34d4dd9fc661">

**Comment by fujiapple852** [comment]
Feature request: https://github.com/ratatui-org/ratatui/issues/1325
PR to implement it: https://github.com/ratatui-org/ratatui/pull/1326
