### ISSUE TITLE
Fix unit tests on i386

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#1317]
Fix tests which fail on i386

https://buildd.debian.org/status/fetch.php?pkg=trippy&arch=i386&ver=0.11.0%2Bdfsg-1&stamp=1727294503&raw=0

```
state::tests::test_scenario::file_ipv4_3probes_3hops_completed_yaml_expects stdout ----
thread 'state::tests::test_scenario::file_ipv4_3probes_3hops_completed_yaml_expects' panicked at crates/trippy-core/src/state.rs:862:47:
assertion `left == right` failed
  left: 781.6666666666666
 right: 781.6666666666665

---- state::tests::test_scenario::file_ipv4_nat_yaml_expects stdout ----
thread 'state::tests::test_scenario::file_ipv4_nat_yaml_expects' panicked at crates/trippy-core/src/state.rs:862:47:
assertion `left == right` failed
  left: 781.6666666666666
 right: 781.6666666666665


failures:
    state::tests::test_scenario::file_ipv4_3probes_3hops_completed_yaml_expects
    state::tests::test_scenario::file_ipv4_nat_yaml_expects
```

**Comment by c-git** [comment]
I will look for it, I think there is an approximately equal assert you can use instead.

**Comment by c-git** [comment]
I don't recall where I saw it. I thought it was std but can't find it. I guess I was mistaken. There are lots of options for float equality but I thought there was one in std, which I can't find. It's easy to find options but let me know if you want me to point out a few.

**Comment by c-git** [comment]
IIRC that only works when the values being subtracted were close to 0 themselves as the EPSILON values changes but  if it works here it's good enough until we need something more.
