### ISSUE TITLE
Better text mode

### ISSUE THREAD

**Issue by Albonycal** [fujiapple852/trippy#1373]
trippy already has a few useful output modes, but I think a normal text based (traceroute like) output will also be handy for cases like copy pasting to an instant messaging platform or email.

 I prefer sending it as text instead of screenshot because it's easier to copy IP addresses and things like that.

**Comment by daryll-swer** [comment]
Agreed, a 'text-mode' that's 1:1 copy/paste ready for professional emails and the like would be great for NOC.

**Comment by c-git** [comment]
Would this be a text version of what would be on the screen (if yes at what point) or some summary type output?

**Comment by c-git** [comment]
If it's the first one there is a flag to preserve the output on exit `--tui-preserve-screen` would that meet your needs?

**Comment by Albonycal** [comment]
> Would this be a text version of what would be on the screen (if yes at what point) or some summary type output?

A summary yes, looks the `-m pretty` option does the trick for email, whatsapp. 
But some platforms mess up the formatting (like Signal, telegram) 

Unfortunately the same problem exists even if you enable the preserve-tui option

**Comment by fujiapple852** [comment]
@Albonycal is the output of `-m markdown` simple enough for Signal et. al.?

```
$ sudo trip 1.1.1.1 -C 2 -m markdown
| Hop | IPs            | Addrs                          | Loss% | Snt | Recv | Last | Avg  | Best | Wrst | StdDev |
|-----|----------------|--------------------------------|-------|-----|------|------|------|------|------|--------|
| 1   | 192.168.1.1    | 192.168.1.1                    | 0.0   | 2   | 2    | 12.6 | 11.7 | 10.7 | 12.6 | 0.9    |
| 2   | 219.79.120.2   | xxx.netvigator.com             | 0.0   | 2   | 2    | 10.0 | 9.8  | 9.6  | 10.0 | 0.2    |
| 3   | 10.193.233.2   | 10.193.233.245                 | 0.0   | 2   | 2    | 8.6  | 8.6  | 8.5  | 8.6  | 0.0    |
| 4   | 10.195.45.190  | 10.195.42.190                  | 0.0   | 2   | 2    | 7.6  | 8.0  | 7.6  | 8.4  | 0.4    |
| 5   | 123.255.90.246 | cloudflare1-lacp-100g.hkix.net | 50.0  | 2   | 1    | 16.0 | 16.0 | 16.0 | 16.0 | 0.0    |
| 6   | 103.22.203.75  | 103.22.203.75                  | 0.0   | 2   | 2    | 9.3  | 9.5  | 9.3  | 9.7  | 0.2    |
| 7   | 1.1.1.1        | one.one.one.one                | 0.0   | 2   | 2    | 11.2 | 10.9 | 10.6 | 11.2 | 0.3    |
```

**Comment by fujiapple852** [comment]
I think you are asking for something like this:

```
traceroute to 1.1.1.1 (1.1.1.1), 64 hops max, 52 byte packets
 1  linksys01983 (192.168.1.1) 5.490 ms  5.305 ms  6.031 ms
 2  xxx.netvigator.com (219.79.120.253) 7.107 ms  7.382 ms  7.685 ms
 3  10.193.223.2 (10.193.233.245) 5.191 ms  4.863 ms  7.155 ms
 4  10.195.12.180 (10.195.42.190) 7.167 ms  5.227 ms  4.817 ms
 5  cloudflare1-lacp-100g.hkix.net (123.255.90.246) 8.318 ms  15.861 ms  0.000 ms
 6  103.22.203.79 (103.22.203.79) 9.304 ms  8.224 ms  7.152 ms
    103.22.203.75 (103.22.203.75) 9.304 ms  8.224 ms  7.152 ms
 7  one.one.one.one (1.1.1.1) 7.066 ms  6.721 ms  6.886 ms
```

**Comment by fujiapple852** [comment]
Another option is to use the `json` mode and feed the output through a template tool like `jinja2`:

```shell
trip -m json | jinja2 my_template.tmpl
```

**Comment by Albonycal** [comment]
Closing this issue, the is a bug on the platform side anyway, they should be parsing these messages better. 
And traceroute works for this :+1:
