### ISSUE TITLE
Move Up Move Down key bind AS VIM 

### ISSUE THREAD

**Issue by zhangshengshan** [fujiapple852/trippy#394]
Move Up bind k 
Move Down bind j
Move Left bind h 
Move right bind l

**Comment by fujiapple852** [comment]
Thanks for raising this @zhangshengshan.  Perhaps it would be good to expand this such that Trippy supports a `~/.trippy.toml` config file in which custom keybindings could be defined?

**Comment by fujiapple852** [comment]
Tracking issue for creating a config file: https://github.com/fujiapple852/trippy/issues/412

**Comment by fujiapple852** [comment]
Fixed via #448

**Comment by fujiapple852** [comment]
@zhangshengshan support for specify keybindings is now also available in the trippy config file, see https://github.com/fujiapple852/trippy/issues/412

**Comment by fujiapple852** [comment]
@zhangshengshan 0.8.0, which support a config file for specifying key bindings, has been released: https://github.com/fujiapple852/trippy/releases/tag/0.8.0
