### ISSUE TITLE
Support light background terminal in TUI mode

### ISSUE THREAD

**Issue by mcint** [fujiapple852/trippy#411]
It looks like TUI mode is the only one that accepts multiple hosts, and that this tool is mainly built around the TUI. How do I use this with a light terminal background? Can I override the color scheme with something akin to LS_COLORS, or a theme flag?

**Comment by fujiapple852** [comment]
Thanks for raising this @mcint, customising the theme isn't something trippy supports today but I like the idea.  

I think the best way to achieve this may be to have a trippy config file (similar to the one I proposed in https://github.com/fujiapple852/trippy/issues/394) that allow specifying a colors for various parts of the TUI, rather than the current hardcoded approach.

What do you think?

**Comment by mcint** [comment]
Thanks for the quick reply, and consideration!

[`bat` does this too](https://github.com/sharkdp/bat#adding-new-themes) (/theme/ in addition to the linked README section). 

I'm less a fan of custom configuration, and one more config file. I would love environment variables, for explicit color setting (/overriding) or also a separate one for theme selection. I frequently find that environment variables are quick to override for exploration or adapting to the demands of a task, and can live in my `.env` file, instead of as another `.config/`.

It looks like you have other reasons for considering a config file, and given the TUI nature of the primary interface, trippy is more primarily used interactively than in shell pipelines. I think I'd recommend a review of other TUIs to make the decision, htop, wireshark, mtr. Maybe I can write a short blog post in review.

I sure wish these theme files could be shared across bat, trippy, *vim, and others, ideally in the same directory, if not built from shared definitions.

**Comment by fujiapple852** [comment]
I agree that Trippy is primarily a Tui application and therefore being able to configure it via the environment makes sense in the spirit of [12 factors app](https://12factor.net/config).  

I would like users to be able to specify any Trippy configuration as config file entries, environment variables or command line arguments (in priority order args -> env -> file).  There are some good rust crates to help with this, though none that I've seen which support Clap natively.  But ultimately this shouldn't be too difficult to piece together manually.

Aside from how it is configured, I've created a PR (https://github.com/fujiapple852/trippy/pull/413) which replaces all the hardcoded Tui colors with a `TuiTheme`.  This theme is not yet exposed via config and the colors are hardcoded to match the current Trippy style.  

This was a useful exercise as it forced me to think about the specific color theme parameter that will be exposed in the configuration.  Currently the theme allows customising the following:

```rust
pub struct TuiTheme {
    /// The default background color.
    ///
    /// This may be overridden for specific components.
    bg_color: Color,
    /// The default color of borders.
    ///
    /// This may be overridden for specific components.
    border_color: Color,
    /// The default color of text.
    ///
    /// This may be overridden for specific components.
    text_color: Color,
    /// The color of the text in traces tabs.
    tab_text_color: Color,
    /// The background color of the hops table header.
    hops_table_header_bg_color: Color,
    /// The color of text in the hops table header.
    hops_table_header_text_color: Color,
    /// The color of text of active rows in the hops table.
    hops_table_row_active_text_color: Color,
    /// The color of text of inactive rows in the hops table.
    hops_table_row_inactive_text_color: Color,
    /// The color of the selected series in the hops chart.
    hops_chart_selected_color: Color,
    /// The color of the unselected series in the hops chart.
    hops_chart_unselected_color: Color,
    /// The color of the axis in the hops chart.
    hops_chart_axis_color: Color,
    /// The color of bars in the frequency chart.
    frequency_chart_bar_color: Color,
    /// The color of text in the bars of the frequency chart.
    frequency_chart_text_color: Color,
    /// The color of the samples chart.
    samples_chart_color: Color,
    /// The background color of the help dialog.
    help_dialog_bg_color: Color,
    /// The color of the text in the help dialog.
    help_dialog_text_color: Color,
}
```

You could imagine, therefore, being able to override the `frequency_chart_bar_color` via something like (mockup):

Command line argument:

```
trip --tui-theme-frequency-chart-bar-color Red
```

Environment variable:

```
TRIP_TUI_THEME_FREQUENCY_CHART_BAR_COLOR=Blue
```

Config file:

```
[theme]
frequency_chart_bar_color=#31c2fc
```

**Comment by fujiapple852** [comment]
@mcint I've updated the PR (https://github.com/fujiapple852/trippy/pull/413) to expose the above theme configuration options via command line arguments:

```
      --tui-theme-bg-color <TUI_THEME_BG_COLOR>
          The default background color [default: black]
      --tui-theme-border-color <TUI_THEME_BORDER_COLOR>
          The default color of borders [default: gray]
      --tui-theme-text-color <TUI_THEME_TEXT_COLOR>
          The default color of text [default: gray]
      --tui-theme-tab-text-color <TUI_THEME_TAB_TEXT_COLOR>
          The color of the text in traces tabs [default: green]
      --tui-theme-hops-table-header-bg-color <TUI_THEME_HOPS_TABLE_HEADER_BG_COLOR>
          The background color of the hops table header [default: white]
      --tui-theme-hops-table-header-text-color <TUI_THEME_HOPS_TABLE_HEADER_TEXT_COLOR>
          The color of text in the hops table header [default: black]
      --tui-theme-hops-table-row-active-text-color <TUI_THEME_HOPS_TABLE_ROW_ACTIVE_TEXT_COLOR>
          The color of text of active rows in the hops table [default: gray]
      --tui-theme-hops-table-row-inactive-text-color <TUI_THEME_HOPS_TABLE_ROW_INACTIVE_TEXT_COLOR>
          The color of text of inactive rows in the hops table [default: dark-gray]
      --tui-theme-hops-chart-selected-color <TUI_THEME_HOPS_CHART_SELECTED_COLOR>
          The color of the selected series in the hops chart [default: green]
      --tui-theme-hops-chart-unselected-color <TUI_THEME_HOPS_CHART_UNSELECTED_COLOR>
          The color of the unselected series in the hops chart [default: gray]
      --tui-theme-hops-chart-axis-color <TUI_THEME_HOPS_CHART_AXIS_COLOR>
          The color of the axis in the hops chart [default: dark-gray]
      --tui-theme-frequency-chart-bar-color <TUI_THEME_FREQUENCY_CHART_BAR_COLOR>
          The color of bars in the frequency chart [default: green]
      --tui-theme-frequency-chart-text-color <TUI_THEME_FREQUENCY_CHART_TEXT_COLOR>
          The color of text in the bars of the frequency chart [default: gray]
      --tui-theme-samples-chart-color <TUI_THEME_SAMPLES_CHART_COLOR>
          The color of the samples chart [default: yellow]
      --tui-theme-help-dialog-bg-color <TUI_THEME_HELP_DIALOG_BG_COLOR>
          The background color of the help dialog [default: blue]
      --tui-theme-help-dialog-text-color <TUI_THEME_HELP_DIALOG_TEXT_COLOR>
          The color of the text in the help dialog [default: gray]
```

The supported colors are `Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White` or specify a hex value (i.e. `ffffff` for white).

If would be great if you were able to give that a try and give some feedback on whether it allows you to customise the theme as you would like.  If so then I'd look to merge this.  

Obviously it is impractical to specify so many theme parameters from the command line, so the next step would be to expose these, and other trippy config, as both config files and environment variable as as described above.

**Comment by mcint** [comment]
That does suffice. Thanks for pushing it through.

**Comment by fujiapple852** [comment]
Reworked the config to avoid having one config option per theme-able item: https://github.com/fujiapple852/trippy/pull/443

**Comment by fujiapple852** [comment]
@mcint support for specify theme colors is now also available in the trippy config file, see https://github.com/fujiapple852/trippy/issues/412

**Comment by fujiapple852** [comment]
@mcint 0.8.0, which includes a config file for specifying TUI themes, to has been released: https://github.com/fujiapple852/trippy/releases/tag/0.8.0

**Comment by fujiapple852** [comment]
@Enter-tainer I'm open to the idea of adding themes. In fact, when the above was added it was named `--tui-theme-colors` to leave open the option to add broader `--theme` flag later.

There are some design questions to resolve first however. Where would themes be defined? Would they be built-in or user defined or both? 

Most importantly, we need someone to design some themes!

Would you be able to define a "light mode" theme? What I would need, for each theme, is a name and values for _all_ of the items below (ANSI colors only for any builtin theme i'd say).

```
# Tui color theme configuration.
#
# The supported ANSI color values are:
#   Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed,
#   LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White
#
# In addition, CSS named colors (i.e. SkyBlue) and raw hex values (i.e. ffffff)
# may be used but note that these are only supported on some platforms and
# terminals and may not render correctly elsewhere.
#
# Color names are case-insensitive and may contain dashes.
#
# See https://github.com/fujiapple852/trippy#theme-reference for details.
[theme-colors]
bg-color = "black"
border-color = "gray"
text-color = "gray"
tab-text-color = "green"
hops-table-header-bg-color = "white"
hops-table-header-text-color = "black"
hops-table-row-active-text-color = "gray"
hops-table-row-inactive-text-color = "darkgray"
hops-chart-selected-color = "green"
hops-chart-unselected-color = "gray"
hops-chart-axis-color = "darkgray"
frequency-chart-bar-color = "green"
frequency-chart-text-color = "gray"
flows-chart-bar-selected-color = "green"
flows-chart-bar-unselected-color = "darkgray"
flows-chart-text-current-color = "lightgreen"
flows-chart-text-non-current-color = "white"
samples-chart-color = "yellow"
samples-chart-lost-color = "red"
help-dialog-bg-color = "blue"
help-dialog-text-color = "gray"
settings-dialog-bg-color = "blue"
settings-tab-text-color = "green"
settings-table-header-text-color = "black"
settings-table-header-bg-color = "white"
settings-table-row-text-color = "gray"
map-world-color = "white"
map-radius-color = "yellow"
map-selected-color = "green"
map-info-panel-border-color = "gray"
map-info-panel-bg-color = "black"
map-info-panel-text-color = "gray"
info-bar-bg-color = "white"
info-bar-text-color = "black"
```
