### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by Nirvanatin** [fujiapple852/trippy#438]
Hi there! In order to build trippy on Windows, I am not sure where to begin. What are the steps for building the binaries on a Windows machine? Thank you!

**Comment by fujiapple852** [comment]
@Nirvanatin windows support was very recently merged and will be in the next release (0.7.0) of trippy, which should available soon.  This will include pre-built binaries and winget packaging. 

In the mean time if you’d like to try it out you can build it from source by:

- Install Rust (https://www.rust-lang.org/tools/install)

- Clone the repo with:
```
git clone https://github.com/fujiapple852/trippy.git
```
- From the `trippy` folder run:
``` 
cargo build —release
```

- Run the trippy build from the `target\release` folder:
```
target\release\trip.exe
```

Remember to run as Administrator and to allow trip.exe in Windows defender, which may block icmp traffic by default.

**Comment by fujiapple852** [comment]
@Nirvanatin you can find the windows binary in the 0.7.0 release:

https://github.com/fujiapple852/trippy/releases/tag/0.7.0

Please let us know how you get on.

**Comment by fujiapple852** [comment]
@Nirvanatin I’ll assume you have what you need now and so close this, feel free to reopen if you have further questions.
