### ISSUE TITLE
Try to resolve AS info for IP addresses without PTR

### ISSUE THREAD

**Issue by hexchain** [fujiapple852/trippy#479]
Currently, if an IP address of a hop does not have a reverse record, then its AS info also won't be looked up. This seems like a pretty strange limitation.

Would it be sensible to enable AS info lookup for all IP addresses, regardless of whether PTR exists?

**Comment by fujiapple852** [comment]
Thanks @hexchain, I agree that it makes sense to try and lookup AS info for all IP addresses.  

I'll include this in the next release, if you want to try it out now you can build from https://github.com/fujiapple852/trippy/pull/480

**Comment by fujiapple852** [comment]
Aside: Trippy looks up additional data about each AS, specifically:

```
pub struct AsInfo {
    pub asn: String,
    pub prefix: String,
    pub cc: String,
    pub registry: String,
    pub allocated: String,
    pub name: String,
}
```

Currently only `asn` (i.e. `AS15169`) is displayed, but we could display and/all of the other fields.  Most useful is `name` (i.e. `"GOOGLE, US"`) but this is often quite long so perhaps not well suited to be displayed in Trippy.

**Comment by fujiapple852** [comment]
@hexchain 0.8.0 which includes this change has been released: https://github.com/fujiapple852/trippy/releases/tag/0.8.0
