### ISSUE TITLE
[Praise} seriously impressed with this project

### ISSUE THREAD

**Issue by m040601** [fujiapple852/trippy#566]
That's it. This in so issue. Just a big thank you for all your work in this tool.

I'm a serious CLI/TUI addict. And I am also a litttle "alergic" to the ... you should try this new tool, because ... it's written in Rust ... blazing fast ... uses GPU ... replaces "deprecated old tools"

But this trippy thing got me hooked. I'm on Archlinux, so I get very fresh latest packages. Today I saw,

> ..., Trippy features a new interactive map ....This screen displays a world map and plots...

> trip www.example.com --geoip-mmdb-file GeoLite2-City.mmdb --tui-geoip-mode short

Wow ... I'm now like a child in a terminal candy store !!! 

Seriously now, really impressed with all the other feature set. Keep up the good work.

**Comment by fujiapple852** [comment]
Thank you @m040601, you just made my day :)

Kudos for the world map has to go to the author of [tui-rs](https://github.com/fdehau/tui-rs), i'm standing on the shoulders of giants!

It would be great if you could help to [spread the word](https://twitter.com/FujiApple852/status/1658124098243899394), having more users on a diverse range of platforms is the best way to flush out all the bugs and make trippy better for everyone.  And of course, PR's always welcome :)

As it happens I was planning to post on /r/rust later today, i'll link to it here after I do.

Thanks again for your kind words!

**Comment by fujiapple852** [comment]
Posted: https://www.reddit.com/r/rust/comments/13j756x/media_introducing_trippy_a_network_diagnostic_tool/

**Comment by cdstanford** [comment]
+1, amazing project!
