### ISSUE TITLE
No Response lines on an iphone hotspot

### ISSUE THREAD

**Issue by cdstanford** [fujiapple852/trippy#567]
Hello,

I'm getting a bunch of "No Response" lines when running over an iPhone hotspot, compared to a traceroute which shows a slightly different picture. Is this expected behavior?
Sample output:
```
╭────────────────────────────────────── Trippy v0.8.0 ───────────────────────────────────────╮
│Target: 172.20.10.2 (172.20.10.2) -> google.com (142.250.191.78)   2023-05-16T16:25:54-07:00│
│Config: protocol=icmp(v4) as-info=n/a details=off max-hosts=auto          help settings quit│
│Status: Running, discovered 11 hops                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
╭Hops────────────────────────────────────────────────────────────────────────────────────────╮
│#  Host                                   Loss Snt  Recv Last Avg  Best Wrst StDe Sts       │
│1  172.20.10.1                            0.0% 6    6    6.2  11.9 5.2  22.2 6.4  🟢        │
│2  No response                            100. 6    0                             🟤        │
│3  No response                            100. 6    0                             🟤        │
│4  No response                            100. 6    0                             🟤        │
│5  No response                            100. 6    0                             🟤        │
│6  No response                            100. 6    0                             🟤        │
│7  No response                            100. 6    0                             🟤        │
│8  No response                            100. 6    0                             🟤        │
│9  No response                            100. 6    0                             🟤        │
│10 No response                            100. 6    0                             🟤        │
│11 nuq04s43-in-f14.1e100.net              0.0% 6    6    58.5 57.7 37.9 100. 16.8 🟢        │
│                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
```

`traceroute` displays a bit more information in comparison:

```
% traceroute google.com
traceroute to google.com (142.250.191.46), 64 hops max, 52 byte packets
 1  172.20.10.1 (172.20.10.1)  8.468 ms  13.725 ms  30.500 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  10.166.67.69 (10.166.67.69)  48.729 ms  47.142 ms  37.035 ms
 7  10.177.76.33 (10.177.76.33)  42.965 ms  34.425 ms  29.186 ms
 8  209.85.174.12 (209.85.174.12)  52.439 ms  74.057 ms  79.099 ms
 9  * * *
10  142.251.224.172 (142.251.224.172)  54.970 ms
    142.251.65.166 (142.251.65.166)  61.603 ms
    142.251.228.80 (142.251.228.80)  37.210 ms
11  108.170.243.14 (108.170.243.14)  45.696 ms  27.451 ms  67.901 ms
12  72.14.237.160 (72.14.237.160)  41.502 ms
    74.125.253.149 (74.125.253.149)  63.871 ms
    nuq04s42-in-f14.1e100.net (142.250.191.46)  50.073 ms
```

(I hope neither of the above have anything super private lol)

I don't see this behavior when connecting over my usual wireless connection.

Awesome work on this tool! I've really enjoyed playing around with it this far.

**Comment by fujiapple852** [comment]
@cdstanford can you tell me what platform you are running on?  

The `traceroute` program on many platforms uses UDP by default, whereas Trippy uses ICMP by default, which may explain the difference.  One thing to try would be to run `trip --udp google.com` and see how that compares.  

Somewhat related; as you can see from the traceroute output above there are multiple hosts responding for some hops, (i.e. hop 10) which would suggest ECMP routing, which I'd expect for a prominent site like google.  

One way that Trippy can help here is to force all probes to go via the same path using either `dublin` or `paris` tracing strategy, so you can try running something like `trip --udp -R dublin -S 5000 -P 33000 google.com` to get a single trace.

**Comment by cdstanford** [comment]
ah cool! Yeah, adding `--udp` makes it match up with the `traceroute` output. Thanks!
The `No Response` corresponds to `* * *` lines which are [common in traceroute](https://webmasters.stackexchange.com/questions/17793/what-does-an-asterisk-star-in-traceroute-mean) so this looks like expected behavior.
For the `dublin` example command you gave I get only 2 hops and then the route is cut off. Same for replacing `dublin` with `paris`
```
1  172.20.10.1                             0.0% 3    3    9.9  18.2 9.9  28.5 7.3  🟢          │
│2  No response                             100. 3    0                             🔴          │
│
```

**Comment by fujiapple852** [comment]
Glad we could resolve it @cdstanford!

I'm interested in the `dublin` result, as that is not what I would expect, would you mind running a diagnostic?

```
trip --udp -R dublin -S 5000 -P 33000 -m silent -C 2 -v --log-format chrome --log-span-events full google.com > trippy.log
```

A rather complicated command!  To break it down, this will run with:
- UDP mode
- Dublin tracing strategy with fixed src (5000) and fixed dest (33000) ports for all probes
- Silent mode (no tracing output)
- Runs for exactly 2 round
- Verbose debug logging, in chrome format, with full span info

If you can send me the trippy.log I may be able to diagnose what is going on here.

**Comment by cdstanford** [comment]
@fujiapple852 here's the log from that command -- [trippy.log](https://github.com/fujiapple852/trippy/files/11510754/trippy.log)

**Comment by fujiapple852** [comment]
Thank you @cdstanford !

The tracing log is _strange_, each round received exactly the same 6 responses, for TTL 1 thought 6 (sequence 33000 to 33005 for the 1st round):

```
33000: 148.64.112.1
33001: 148.64.112.1
33002: 64.201.240.48
33003: 64.201.240.38
33004: 64.201.240.41
33005: 206.223.116.21
```

Oddly, the IP `148.64.112.1` responds to _both_ the first two probes (TTL 1 and TTL 2).  

```
IP: 148.64.112.1
Host: lo0.asbr01-2ndst720-oak.paxio.net
AS Name: AS36734 PAXIO-SFBA, US
AS Info: 148.64.112.0/20 arin 2017-08-30
Geo: Emeryville, California, United States, North America
```

I don't see `172.20.10.1` at all (the single host shown in your output), which makes me think there must be some other difference between the test runs.  It also doesn't make sense that Trippy would only show 1 hop when it has received 6 responses.  It could be that the routing differs between your initial attempt and the debug attempt.  

If you were willing, i'd love to see another couple of examples, this time with slightly modified commands:

```
trip --udp -R dublin -S 5000 -P 33000 -m pretty -C 2 -v --log-format chrome --log-span-events full google.com > trippy2.log
```

```
trip --udp -R dublin -S 5000 -P 6000 -m pretty -C 2 -v --log-format chrome --log-span-events full google.com > trippy3.log
```

**Comment by cdstanford** [comment]
sure! certainly happy to run more diagnostic commands :)
[trippy2.log](https://github.com/fujiapple852/trippy/files/11519073/trippy2.log)
[trippy3.log](https://github.com/fujiapple852/trippy/files/11519074/trippy3.log)

**Comment by cdstanford** [comment]
wait a minute, I messed this up. I think I ran all these on the wrong wifi connection. Let me rerun

**Comment by cdstanford** [comment]
fixed:
[trippy.log](https://github.com/fujiapple852/trippy/files/11519496/trippy.log)
[trippy2.log](https://github.com/fujiapple852/trippy/files/11519497/trippy2.log)
[trippy3.log](https://github.com/fujiapple852/trippy/files/11519498/trippy3.log)

**Comment by fujiapple852** [comment]
That's great @cdstanford, appreciate you taking the time to help out.  These logs looks better and match up to the output you saw.

The issue here appears to be that the 2nd hop (10.170.214.221) is resetting the IPv4 [identification](https://en.wikipedia.org/wiki/Internet_Protocol_version_4#Identification) field to zero, and this is the field used by the `dublin` tracing strategy to track probes and responses.  So despite Trippy receiving responses for probes, it is unable to correlate these with the probes that were sent and so they are simply discarded.

This is something that routers are not supposed to do when the "Don't Fragment (DF)" [flag](https://en.wikipedia.org/wiki/Internet_Protocol_version_4#Flags) is set (which Trippy sets), however in the wild west of the internet there are often poorly behaved nodes and, alas, there isn't much that can be done about that, the `dublin` tracing strategy simply won't work with these, but classic tracing will.

Aside: we didn't dig into the `paris` case here, but that is almost certainly not going to work for this network as i'd imagine your mobile operator is placing you behind `cgnat`, as is typical.

Anyway I think we can close this out, thanks again for the help.
