### ISSUE TITLE
Publish musl Linux .deb

### ISSUE THREAD

**Issue by ethanhs** [fujiapple852/trippy#568]
Howdy! 👋 

This is a very cool program!

I am the maintainer of `apt.cli.rs`, an apt repo of Rust cli tools. To keep it as compatible as possible I like to use musl-linked binaries, since they won't run into glibc version compatibility issues. If you publish musl libc linked deb packages, I can add your program to the APT repo!

**Comment by fujiapple852** [comment]
@ethanhs sure we can do that.  The change is merged in #571 and so this will be build for the `0.9.0` release.  For now if you would like a preview to test, you can check the test build here (note that this is an unsupported `0.9.0-dev` build, suitable for testing only and will be deleted after you complete your testing):

https://github.com/trippy-cli/trippy/releases/download/0.103.0/trippy_x86_64-unknown-linux-musl_0.103.0_amd64.deb

**Comment by ethanhs** [comment]
Awesome, thank you for adding that! I'll try to test that package tomorrow.
