### ISSUE TITLE
Replace unmaintained dependency tui with ratatui

### ISSUE THREAD

**Issue by auronandace** [fujiapple852/trippy#569]
I noticed you are still using the `tui` crate. This has not been maintained for quite some time now.

Development has now moved to the drop-in replacement `ratatui`: https://github.com/tui-rs-revival/ratatui

I hope this is helpful for your project.

**Comment by fujiapple852** [comment]
@auronandace Trippy will be using `ratatui` for the `0.9.0` release.  I was waiting for a release with my upstream PR https://github.com/tui-rs-revival/ratatui/pull/159 but I guess there is no harm in swapping out the library now and updating later.
