### ISSUE TITLE
Only create the required sending socket

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#647]
The channel always creates both an `icmp` and `udp` sending socket, regardless of the chosen mode.  Whilst this is not known to be causing an issue it is wasteful.

**Comment by c-git** [comment]
To clarify my understanding, the socket gets created but doesn't get used depending on the mode?

**Comment by fujiapple852** [comment]
@c-git correct; channel.rs needlessly creates both icmp and udp (raw) send sockets, when they are only used in icmp and udp protocol modes respectively.
