### ISSUE TITLE
Add `--icmp` command line shortcut

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#649]
Users may specify `--udp` and `--tcp` as shortcuts to `--protocol udp` (`-p udp`) and `--protocol tcp` (`-p tcp`) respectively.  

For example for `udp`:

```rust
/// Trace using the UDP protocol
#[arg(
    long,
    display_order = 3,
    conflicts_with = "protocol",
    conflicts_with = "tcp"
)]
pub udp: bool,
```

If neither is specified then the `icmp` protocol is chosen by default:

 ```rust
/// The default value for `protocol`.
pub const DEFAULT_STRATEGY_PROTOCOL: Protocol = Protocol::Icmp;
```

```rust
let protocol = cfg_layer(
    args.protocol,
    cfg_file_strategy.protocol,
    constants::DEFAULT_STRATEGY_PROTOCOL,
);
```

However the protocol may also be specified in the config file:

```
#
# Tracing strategy configuration.
#
[strategy]

# The tracing protocol.
#
# Allowed values are:
#   icmp [default]
#   udp
#   tcp
protocol = "icmp"
```

The user may wish to override the value from the config file with another protocol specified via the command line.  To do so for `icmp` the user must use the longer `--protocol icmp` (`-p icmp`) form as there is no `--icmp` shortcut.  Therefore it would be useful to add a `--icmp` command line shortcut.

**Comment by trkelly23** [comment]
I will be testing the changes and might need a few questions answered.  Where should I post them, here?

**Comment by fujiapple852** [comment]
@trkelly23 here is fine or you can find me on discord or matrix (same username)
