### ISSUE TITLE
Trippy v0.8.0 Windows 11

### ISSUE THREAD

**Issue by packetloss69** [fujiapple852/trippy#656]
Hi. Great tool.
Installation in Windows 11 went smoothly with - winget install trippy
Running as admin, currently Trippy produces no output.  (_Awaiting data..._)
_Status: Running, discovered 0 hops_

Tracert etc. works as expected on same machine.

DNS seems to resolve ok.
Hostname resolution etc is fine.

How can i help?

**Comment by fujiapple852** [comment]
Hey there @packetloss69 (great name!) thanks for the report and offer of help.

This is very likely to be Windows defender (or a 3rd party AV product) blocking ICMP responses.  It could also be some corporate policy applied to your machine if you're in such an environment (i.e. a workplace or education establishment).

I don't have access to a physical Windows machine to try it out, only a Windows VM. 

See https://github.com/fujiapple852/trippy/issues/578 for a very similar issue reported on Windows 10.  

If you could please try the same troubleshooting steps I outlined in the linked issue and report back that would be great.

**Comment by packetloss69** [comment]
Hi. Yes. You are correct. 
Inbound ICMPv4 - all ICMP types indeed solved the issue.
Thank you.

**Comment by fujiapple852** [comment]
Ok that’s great, thanks for confirming.
