### ISSUE TITLE
armv7 binaries are not available

### ISSUE THREAD

**Issue by patrickelectric** [fujiapple852/trippy#712]
Raspberry pi 3 and others are still being sold and available.

**Comment by c-git** [comment]
?

**Comment by fujiapple852** [comment]
Rust [supports](https://doc.rust-lang.org/nightly/rustc/platform-support.html) the following `armv7` targets (all tier 2):

- `armv7-unknown-linux-gnueabihf`
- `armv7-unknown-linux-musleabihf`
- `armv7-unknown-linux-musleabi`

**Comment by fujiapple852** [comment]
All three targets added in #810 and will be available in the `0.9.0` release.
