### ISSUE TITLE
Export DNS resolver for library usage

### ISSUE THREAD

**Issue by crisidev** [fujiapple852/trippy#754]
Hello,
I am wondering if you would be open to exporting the DNS resolver to be used as a library and not only by the main TUI / Stream / etc.

I would be already pretty happy to just have a `pub mod dns` inside `lib.rs`. What do you think?

**Comment by fujiapple852** [comment]
@crisidev I think we should be able to do this, i'm just not sure what the right approach is.

Trippy is intended primarily as a _tool_ but is structured as a tool built on top of a _library_, such that other tools could be build using the Trippy library.

In fact there is an (out of date) pr (#640) to split Trippy into different crates which may or may not happen, i'm still unsure if it is a good idea or not.  See [this](https://github.com/fujiapple852/trippy/pull/640#issuecomment-1700994722) comment for my thoughts on the topic.

So right now the library portion of Trippy does not deal with DNS at all and so the dns module is not part of the library, but is part of the tool.  Therefore it doesn't make sense to re-export it in lib.rs, even though it would be trivial to do so.

I should point out that the DNS resolver in Trippy is simply wrapper on top of the `dns-lookup` and `trust-dns-resolver` (recently rebranded as `hickory-resolver`) crates which do all the heavy lifting.  The only things that Trippy adds is lazy background lookups and ASN lookups, which I guess maybe useful to other projects?  If not then I'd recommend using those crates directly.

Aside: I would actually like to divest `hickory-resolver` as it is an async only library which forces Trippy to pull in the whole `tokio` eco-system which bloats the final executable size by a large multiple.  However I am yet to find a suitable replacement library that is cross platform, non-async and of high quality so for now we stick with what we have.

**Comment by fujiapple852** [comment]
I think that given:
- Trippy is pre-1.0 and perma-unstable at this point
- No decision has been made about how to structure it going forward
- This is a trivial change

Then I'm ok with it for now.

PR up: #756 and this will go into `0.9.0`.

**Comment by c-git** [comment]
You said trivial and I just looked at the PR and I'm like that was a lot. It's easy for you, but it's actually not easy. Required a good understanding of what needed to move where.

**Comment by fujiapple852** [comment]
Fair point @c-git !

There was one complication that may be worth explaining as it crops up from time to time.  

The `DnsResolveMethod` enum was shared between the `config` and `dns` modules.  By moving the `dns` module into the library (and out of the tool) I had to move the `DnsResolveMethod` into the `dns` module as well.

However in the `dns` we do not want to have to specify attributes such as `ValueEnum`, `Deserialize` and `#[serde(rename_all = "kebab-case")]` which are needed in the `config` module to support being read from a config file.

The solution is to duplicate the type into `DnsResolveMethodConfig` and `DnsResolveMethod` and and provide a conversion from the former to the latter.

This pattern is repeated for types in the `tracing/config.rs` module which have the same issue.

**Comment by c-git** [comment]
Thanks for explaining that I wasn't quite following what was happening. Thought I'd have to play with it a bit to understand. Thanks for saving me the time.

**Comment by fujiapple852** [comment]
@crisidev I did some further refactoring of the dns module to make it more suitable to be part of the public interface.  I'll merge it now as it is, please me know if it works for you.
