### ISSUE TITLE
Add `--tui-privacy-max-ttl` flag to hide host and IP details for low ttl hops

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#766]
This is desirable when sharing screenshots, videos or text copies of a Trippy Tui screen and you wish to hide local hops which may contain sensitive information such as IP address, hostname and GeoIP data.

In the example below all hops with ttl <= 4 were masked by adding the new `--tui-privacy-max-ttl 4` command line argument.  This can also also be set in the config file as usual.  The default value is 0, meaning no hops will be privacy masked.

<img width="750" alt="Screenshot 2023-11-09 at 8 34 38 PM" src="https://github.com/fujiapple852/trippy/assets/36075719/44b2f497-dcdc-4422-aabf-30ef89b868ee">

Both the normal and hop detail navigation mode will be masked:

<img width="751" alt="Screenshot 2023-11-09 at 8 40 01 PM" src="https://github.com/fujiapple852/trippy/assets/36075719/68137fd5-020f-47fc-81ee-d1d605d6477f">

The world map is also masked for Geo IP data:

<img width="753" alt="Screenshot 2023-11-09 at 8 39 49 PM" src="https://github.com/fujiapple852/trippy/assets/36075719/aa7efe4a-a58b-4e80-b3ec-0e692f1bf6a3">

**Comment by c-git** [comment]
Really cool idea, is it a big step to make this configurable from within the application so like during runtime?

**Comment by fujiapple852** [comment]
It could be done, but would would the UX be for entering the desired `ttl` value?  A pop up with a number entry box?  The only alternative I can think of would be to have keys to increase/decrease the privacy threshold but that feels like overkill for this.

**Comment by c-git** [comment]
I'm not opposed to those options but since I don't think it's something ppl will use often I'd not want to take up valuable hotkeys by default. I'd allow them to be set by the user if the so choose if we decide to go that route. Initially I was just thinking that it would be something that you could change in settings so you wouldn't have to close and reopen the program.

**Comment by fujiapple852** [comment]
Added #771 to cover the possibility of changing some settings at runtime.

**Comment by fujiapple852** [comment]
Follow up enhancement: https://github.com/fujiapple852/trippy/issues/1347
