### ISSUE TITLE
Investigate unusual MPLS example

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#804]
Given the following packet:

```
0000   32 ff 66 fe fe f5 fe 00 00 00 01 01 08 00 45 00
0010   00 a8 42 f3 00 00 f8 01 dd a0 3e 73 70 f4 9f 41
0020   53 18 0b 00 f4 ee 00 11 00 00 45 00 00 54 00 00
0030   40 00 02 01 50 75 9f 41 53 18 5d b8 d8 22 08 00
0040   78 f8 fe 18 80 ee 00 00 00 00 00 00 00 00 00 00
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00a0   00 00 00 00 00 00 00 00 00 00 20 00 78 56 00 08
00b0   01 01 65 9f 01 01
```

This is an IPv4 packet (shown here with the ethernet header) whose payload is an ICMP `TimeExceeded` (TE) packet.  The TE packet contains the "original datagram" (a nested IPv4 packet and the corresponding original ICMP `EchoRequest` packet) as is usual.  

The TE packet also appears to contain an ICMP Multi-part Extensions Object, specifically a MPLS object with a single stack with a label of 416240.  However the interpretation is not clear given the TE packet has an rfc4884 "length" field set to be 17.

Both `Wireshark` (and `tshark`) and Trippy interpret this as an invalid ICMP extension, however `tcpdump` is able to extract the MPLS stack and label.

`tcpdump` (v4.99.4) reports:

```
12:47:08.226646 IP (tos 0x0, ttl 248, id 17139, offset 0, flags [none], proto ICMP (1), length 168)
    62.115.112.244 > 159.65.83.24: ICMP time exceeded in-transit, length 148
	IP (tos 0x0, ttl 2, id 0, offset 0, flags [DF], proto ICMP (1), length 84)
    159.65.83.24 > 93.184.216.34: ICMP echo request, id 65048, seq 33006, length 64
	ICMP Multi-Part extension v2, checksum 0x7856 (correct), length 12
	  MPLS Stack Entry Object (1), Class-Type: 1, length 8
	    label 416240, tc 0, [S], ttl 1
```

Both `Wireshark` (4.2 on macOS) and `tshark` (4.0.8 on Linux) reports:

```
Frame 44: 182 bytes on wire (1456 bits), 182 bytes captured (1456 bits)
    Encapsulation type: Ethernet (1)
    Arrival Time: Nov 20, 2023 12:47:08.226646000 UTC
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1700484428.226646000 seconds
    [Time delta from previous captured frame: 0.002536000 seconds]
    [Time delta from previous displayed frame: 0.002536000 seconds]
    [Time since reference or first frame: 1.734349000 seconds]
    Frame Number: 44
    Frame Length: 182 bytes (1456 bits)
    Capture Length: 182 bytes (1456 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:icmp:ip:icmp:data]
Ethernet II, Src: fe:00:00:00:01:01 (fe:00:00:00:01:01), Dst: 32:ff:66:fe:fe:f5 (32:ff:66:fe:fe:f5)
    Destination: 32:ff:66:fe:fe:f5 (32:ff:66:fe:fe:f5)
        Address: 32:ff:66:fe:fe:f5 (32:ff:66:fe:fe:f5)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: fe:00:00:00:01:01 (fe:00:00:00:01:01)
        Address: fe:00:00:00:01:01 (fe:00:00:00:01:01)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 62.115.112.244, Dst: 159.65.83.24
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 168
    Identification: 0x42f3 (17139)
    000. .... = Flags: 0x0
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 248
    Protocol: ICMP (1)
    Header Checksum: 0xdda0 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 62.115.112.244
    Destination Address: 159.65.83.24
Internet Control Message Protocol
    Type: 11 (Time-to-live exceeded)
    Code: 0 (Time to live exceeded in transit)
    Checksum: 0xf4ee [correct]
    [Checksum Status: Good]
    Unused: 00
    Length: 17
    [Length of original datagram: 68]
    Unused: 0000
    Internet Protocol Version 4, Src: 159.65.83.24, Dst: 93.184.216.34
        0100 .... = Version: 4
        .... 0101 = Header Length: 20 bytes (5)
        Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
            0000 00.. = Differentiated Services Codepoint: Default (0)
            .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
        Total Length: 84
        Identification: 0x0000 (0)
        010. .... = Flags: 0x2, Don't fragment
            0... .... = Reserved bit: Not set
            .1.. .... = Don't fragment: Set
            ..0. .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment Offset: 0
        Time to Live: 2
            [Expert Info (Note/Sequence): "Time To Live" only 2]
                ["Time To Live" only 2]
                [Severity level: Note]
                [Group: Sequence]
        Protocol: ICMP (1)
        Header Checksum: 0x5075 [validation disabled]
        [Header checksum status: Unverified]
        Source Address: 159.65.83.24
        Destination Address: 93.184.216.34
    Internet Control Message Protocol
        Type: 8 (Echo (ping) request)
        Code: 0
        Checksum: 0x78f8 [unverified] [in ICMP error packet]
        [Checksum Status: Unverified]
        Identifier (BE): 65048 (0xfe18)
        Identifier (LE): 6398 (0x18fe)
        Sequence Number (BE): 33006 (0x80ee)
        Sequence Number (LE): 61056 (0xee80)
        Data (56 bytes)

0000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0030  00 00 00 00 00 00 00 00                           ........
            Data: 000000000000000000000000000000000000000000000000000000000000000000000000…
            [Length: 56]
    ICMP Multi-Part Extensions (unsupported version)
        Version: 0
        .... 0000 0000 0000 = Reserved: 0x000
        [Checksum: [missing]]
        [Checksum Status: Not present]
```

Analysis:

Given the TE packet has a non-zero value for the rfc4884 "length" field, it is deemed to be a "Compliant Extension" w.r.t. rfc4884.

Wireshark shows:

TE packet: 148 bytes, of which:
  - TE header: 8 bytes
  - TE payload 140 bytes

The TE payload consists of the "original datagram" which is:
  - IPv4 header 20 bytes
  - Original ICMP EchoRequest: 64 bytes, of which:
    - EchoRequest ICMP header: 8 bytes
    - Data payload: 56 bytes
  - ICMP Multi-part extension: 72 bytes

Adding these up we get 156 bytes instead of the expected 140 bytes (20 + 64 + 72 = 156).  However Wireshark is also showing some overlap between the end of the "Data payload" and the "ICMP Multi-part extension" which is confusing.  If we adjust for this, the length of the "ICMP Multi-part extension" is 56 bytes (counted visually!) and so the total is now correct (20 + 64 + 56 = 140).

rfc4884 states that "The length attribute represents length of the padded "original datagram" field, measured in 32-bit words.".  The "length" field of the TE packet is set to be 17 which means that the first 68 bytes (17 * 4 = 68) of TE payload should interpreted as the "original datagram" and the remaining 72 bytes (140 - 68 = 72) as the extensions.  This matches what Wireshark shows us (as well as the logic in Trippy).

Somehow, `tcpdump` determines that the "correct" start for the the extension at offset 60 bytes (72 - 12 = 60) and is therefore able to parse the MPLS extension.

Relevant implementations of `tcpdump` and `Wireshark`:
https://github.com/the-tcpdump-group/tcpdump/blob/master/print-icmp.c
https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-icmp.c

**Comment by ytti** [comment]
This byte string looks ok to me, its location in the packet, I'm not sure, it seems as if there is bunch of zero padding, and I didn't bother figuring out if this is fine or not.

`20 00 78 56 00 08 01 01 65 9f 01 01``

The ICMP extension header 20 00 78 56
  * 2 version, 4bits
  * 000 reserved, 12bits
  * 7856, 32bits checksum

The Extension Object Header 00 08 01 01
  * 00 08 length, 32bits, including object header (excluding icmp extension header) 
  * 01 class-value, 8bits
  * 01 c-type, 8bits
  
The Extension Payload 65 9f 01 01 
  * 659f0, 20bits mpls label
  * 1, 4bits (exp:000 BOS:1)
  * 01, 8bits ttl

**Comment by ytti** [comment]
https://datatracker.ietf.org/doc/html/rfc4884#section-5

I think this explains the padding. The original embedded packet is exactly 128B, even though it's actually 18B shorter, so to get it to 128B, 18B of zeroes were added. 

The ICMP EO is after the padded embedded packet.

**Comment by fujiapple852** [comment]
@ytti yes it is right that senders will do this padding, the question is how the receiver will parse the message, specifically a _compliant_ vs _non-compliant_ implementation processing a _compliant_ message (i.e. one where the sender has set the "length" attribute).

I think I know what is going on.

One thing that jumped out at me today when I re-read this thread (with fresher eyes!) is that the TE payload is 140 bytes and the MLPS object is 12 bytes and 140 - 12 = 128 which is the magic number.

[From section 5.3](https://datatracker.ietf.org/doc/html/rfc4884#section-5.3):

> When a non-compliant application receives a message that contains
   compliant ICMP extensions, it will parse those extensions correctly
   only if the "original datagram" field contains exactly 128 octets.
   This is because non-compliant applications are insensitive to the
   length attribute that is associated with the "original datagram"
   field.  (They assume its value to be 128.)

Therefore I believe `tcpdump` can be classified as a "non-compliant" implementation as it is "insensitive to the length attribute" whereas both Trippy and Wireshark are compliant implementations and respect the "length" attribute (17 * 4 = 68 in this example) and therefore fail to parse the extension.  Looking at the [code](https://github.com/the-tcpdump-group/tcpdump/blob/master/print-icmp.c#L250-L260) I don't see `tcpdump` handling this at all other than [this](https://github.com/the-tcpdump-group/tcpdump/blob/master/print-icmp.c#L751-L756) case.

I did a quick test in Trippy and by _ignoring_ the "length" attribute of the _compliant_ TE packet, the alternative logic for a _compliant_ application to process a (not actually) _non-compliant_ message kicks in (i.e. assume its at offset 128) and we are able to parse the extension.

The question is, what is the right behaviour for Trippy?

I notice Wireshark has a [setting](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-icmp.c#L1739-L1743) related to this, I tried it and it didn't seem to change anything.

**Comment by ytti** [comment]
I think what you are saying, is that the DO node which generated the TTL exceeded message, can be assumed to be compliant, because it added padding and added ICMP EO. However, you are also saying, that it should have set the TTL exceeded message `length` type to a higher value than it did, that it incorrectly didn't include the padding bytes in the `length`. 

So you are saying, this particular implementation is only partially correct. And tcpdump happens to work, because it doesn't rely on the length field for logic. 

Personally I'm not sure why there would be benefit relying in the length field. But if I understood you correctly, you could approach DO and ask them about this message, if they believe it to be correct.

**Comment by fujiapple852** [comment]
> the DO node...

Nit: the node which generates this (questionable) EO is 62.115.112.244 (AS1299 nyk-bb1-link.ip.twelve99.net), the recipient is a DO node I run.

> ...which generated the TTL exceeded message, can be assumed to be compliant, because it added padding and added ICMP EO

Not quite, the way i've explained it in the code is:

```rust
// We have a 'compliant' ICMP extension as defined by rfc4884.
//
// Specifically, it specifies a non-zero `length` attribute of at
// least 128 octets.
//
// From rfc4884 (section 3) entitled "Summary of Changes to ICMP":
//
// "When the ICMP Extension Structure is appended to an ICMP message
// and that ICMP message contains an "original datagram" field, the
// "original datagram" field MUST contain at least 128 octets."
//
// Therefore, we assume that any non-zero `length` attribute less
// than 128 octets is a non-compliant message.
```

> However, you are also saying, that it should have set the TTL exceeded message length type to a higher value than it did, that it incorrectly didn't include the padding bytes in the length.

Yes that's right, based on my interpretation of the section quoted.

> And tcpdump happens to work, because it doesn't rely on the length field for logic.

Seemingly so yes, but I'll have to dig more into the `tcpdump` code to be sure. 

> Personally I'm not sure why there would be benefit relying in the length field

It allows for an EO to be safely added to a TE message with an original datagram > 128 octets.  As rfc4884 says:

>    Unfortunately, the "original datagram" field lacks a length
   attribute.  Application software infers the length of this field from
   the total length of the ICMP message.  If an extension structure were
   appended to the message without adding a length attribute for the
   "original datagram" field, the message would become unparsable.
   Specifically, application software would not be able to determine
   where the "original datagram" field ends and where the extension
   structure begins.

**Comment by ytti** [comment]
It does feel ambiguous. 

1) include padding in length
   * we cannot tell for packets under 128B what part, if any, is padding and what is message

2) do not include padding in length
   * if we see length is below 128B, we know it'll also, in addition, contain padding to go to 128B, because RFC says so.
   * we know what part is message, what part is padding and what part is EO
   * so we implicitly read 128-length after the end of the embedded packet, when it's below 128

I can see how people can arrive to either conclusion, and I guess proof is in the the captures.

**Comment by fujiapple852** [comment]
@ytti The is the logic I've ended up with*, which passes the tests I've created covering the various packets observed in the wild.  Would appreciate a review.  Thanks again!

```rust
    pub fn split(rfc4884_length: u8, icmp_payload: &[u8]) -> (&[u8], Option<&[u8]>) {
        let orig_datagram_length = usize::from(rfc4884_length * 4);
        if orig_datagram_length > icmp_payload.len() {
            return (&[], None);
        }
        if icmp_payload.len() > ICMP_ORIG_DATAGRAM_MIN_LENGTH {
            if orig_datagram_length > ICMP_ORIG_DATAGRAM_MIN_LENGTH {
                // a 'compliant' ICMP extension as defined by rfc4884.
                do_split(orig_datagram_length, icmp_payload)
            } else if orig_datagram_length > 0 {
                let (payload, ext) = do_split(ICMP_ORIG_DATAGRAM_MIN_LENGTH, icmp_payload);
                // a 'compliant' ICMP extension padded to at least 128 octets.
                (&payload[..orig_datagram_length.min(payload.len())], ext)
            } else {
                // a 'non-compliant' ICMP extension padded to 128 octets.
                do_split(ICMP_ORIG_DATAGRAM_MIN_LENGTH, icmp_payload)
            }
        } else {
            // no extension present
            (icmp_payload, None)
        }
    }
```

* Apart from some IPv6 adjustment needed
