### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by isjarvi** [fujiapple852/trippy#845]

**Comment by isjarvi** [comment]
.\trip.exe www.baidu.com -v -m json > rv.txt
[Uploading rv.txt…]()

**Comment by fujiapple852** [comment]
Thank you.

Before we do anything else please confirm that you have read https://github.com/fujiapple852/trippy#why-does-trippy-show-awaiting-data and that you have enabled ICMP traffic in Windows defender.

**Comment by fujiapple852** [comment]
@isjarvi to confirm your situation:

- You run `trip.exe www.baidu.com -m json` on Windows 10 and you get the expected output
- You run `trip.exe www.baidu.com -m json` on Windows 11 and you get the following "empty" output:

```json
{
  "info": {
    "target": {
      "ip": "180.101.50.242",
      "hostname": "www.baidu.com"
    }
  },
  "hops": []
}
```
- You have configured both Windows 10 and Windows 11 to enable ICMP in Windows defender

What the debug logging shows is that Trippy sent 23 ICMP probes per round (for 10 rounds) but did not receive any responses.

This _almost always_ indicates a firewall issue (Windows defender or some other 3rd party firewall or AV tool), however given Trippy has never been tested on Windows 11 then I can't rule out some change in behaviour on Windows 11 that is incompatible with Trippy.  It could also be that the instructions for allowing ICMP traffic in Windows defender that I linked to are incompatible with Windows 11.

As a next step I would suggest you install and run a tool like Wireshark and capture all outgoing and incoming ICMP packets whilst Trippy is running.  This will show us that either (i) response packets are not being received by the OS or (ii) the OS is not delivering those packets to Trippy.

You may also want to try tracing with UDP and TCP to see if that makes a difference.

Looking at the VirtualBox website it claims to support Windows 11 these days and it seems the Windows 11 ISO can be downloaded so I may try to setup a Windows 11 VM to test.

**Comment by fujiapple852** [comment]
@isjarvi I just:

- installed Windows 11 in VirtualBox and then did a 
- Updated winget to 1.6
- Ran `winget install trippy`
- Ran `trip.exe www.baidu.com -m json` -> no output

In then crated the needed Windows Defender rules (as shown in https://github.com/fujiapple852/trippy#why-does-trippy-show-awaiting-data):

- Ran `New-NetFirewallRule -DisplayName "ICMP Trippy Allow" -Name ICMP_TRIPPY_ALLOW -Protocol ICMPv4 -Action Allow`
- Ran `trip.exe www.baidu.com -m json` -> output as expected

<img width="499" alt="Screenshot 2023-12-01 at 11 55 29 PM" src="https://github.com/fujiapple852/trippy/assets/36075719/fa6436cf-d792-425d-9fda-91e976e24441">

<img width="356" alt="Screenshot 2023-12-02 at 12 01 26 AM" src="https://github.com/fujiapple852/trippy/assets/36075719/d8c1446e-7d9e-46f2-a186-cb380900da8f">

Therefore we can conclude that Trippy works as expected on Windows 11.

Please double check your Windows Defender setting and any other firewall or AV product you have installed.

**Comment by c-git** [comment]
I tested it on WIN 11 and it worked for me. I can check again but haven't quite followed everything in this issue yet. Will try to read it in more detail later but just wanted to confirm that I tested the release candidate on Win 11 and it worked for me.

**Comment by fujiapple852** [comment]
I'm going to close this as it does not appear to be an issue with Trippy.
