### ISSUE TITLE
Generation of man pages

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#85]

**Comment by ehaupt** [comment]
[help2man](https://www.gnu.org/software/help2man/) creates a good man page:

```sh
help2man -s 1 -Nn "Network diagnostic tool inspired by mtr" `which trip` -o files/trip.1
```

[Here](https://gist.github.com/ehaupt/4e10f8db8bc1c7d1fe4dbfb3836b6092) is what it generated.

Maybe this would be a start?

**Comment by fujiapple852** [comment]
Hi @ehaupt,

What I had in mind here was using https://github.com/clap-rs/clap/tree/master/clap_mangen since Trippy is already using `clap` (for command line parsing) and `clap_complete` (for generating shell completions).

I haven't given this much thought, but I was imaging this may work in a similar way to the completions, where there is a command such as:

```
trip --generate-man > /path/to/man/pages/trip.1
```

So the command outputs to stdout and the user can redirect it to a file in wherever their man pages are stored.  

Thoughts?

**Comment by ehaupt** [comment]
Clap would also suffice. Regardless, it would be beneficial if the man page were generated during the build process, enabling packagers (I maintain the FreeBSD port) to install it easily.

**Comment by fujiapple852** [comment]
> it would be beneficial if the man page were generated during the build process, enabling packagers (I maintain the FreeBSD port) to install it easily.

That is a valid point @ehaupt.  I think this could be created at build time during a release, i'm just not sure where the generated man page file could be stored, I guess the `Assets` section in the [release note](https://github.com/fujiapple852/trippy/releases/tag/0.10.0]) ?

Given the `help2man` runs _after_ the build then I guess it could (in the future if/when it exists) be modified to be something like:

```
post-build-MANPAGES-on:
	${CARGO_TARGET_DIR}/${CARGO_BUILD_TARGET}/*/trip --generate-man trip.1
```

**Comment by ehaupt** [comment]
I was searching for a method to install man pages using the cargo toolchain. Upon reading https://github.com/rust-lang/cargo/issues/2729, I discovered that this process is not as straightforward as it is with cmake or autotools.

In this context, your proposed solution of adding a --generate-man flag to enable man page generation at runtime appears to be the optimal approach. This allows me to generate the man pages in the post-build section and install them in the post-install section.

**Comment by fujiapple852** [comment]
@ehaupt PR for adding `--generate-man`: https://github.com/fujiapple852/trippy/pull/1089
