### ISSUE TITLE
the docs show how to "use" it, but not how to "use" it, if that makes sense

### ISSUE THREAD

**Issue by unusualevent** [fujiapple852/trippy#853]
Cool tool. Nice docs. I guess they are technically complete?

It shows all the strokes for how to use it,

but not /why/ you'd use each part, or how you'd solve a diagnostic issue.

I guess it shows "how to use it" without giving me a reason to go "here's why I should use it because here's how it solves X, Y, or Z diagnostic problem"

Maybe what I'm asking for is a walkthrough or a pitch?

**Comment by c-git** [comment]
IMO this application gives you information and what you do with it really depends on your use case. For example you might just be monitoring to see how traffic goes between two points and where the failures happen. In this use case you can imagine you are getting several failed pings to some target and you want to see at what point along the journey the messages get "lost". Many people who reach for this probably already know what they want and just want a repeated version of the command line trace route tool.

Another use case (mine) is you need to monitor when a connection goes down. So I plan to try to build on top of this application to send notifications when predefined events occur.

**Comment by c-git** [comment]
Are you able to share your use case and perhaps I could give you my opinion because there are so many that it wouldn't be possible write a walk though for all of them.

**Comment by symgryph** [comment]
adding something like: sudo trip grav.munn.me --dns-lookup-as-info -G /var/lib/GeoIP/GeoLite2-City.mmdb -r cloudflare

To show relevant info would be nice in a quickstart!

**Comment by c-git** [comment]
I like that idea, I think a quick starter is a good idea to add to the readme. I don't think it would address @unusualevent 's issue but I think a section called quick starter is a good idea and we should try to add it (But it does take someone to do it). All the parts of it already exist like the [usage examples](https://github.com/fujiapple852/trippy#usage-examples).

One note though. It isn't necessary to use sudo to run trippy (see [privilages](https://github.com/fujiapple852/trippy#privileges)). I think things like that should be part of the quick start for each platform. I think maybe we should try to promote that option in the quick start as I feel it's generally safer to give trippy only the permissions is needs (I think in general you should use the least privileges possible to accomplish what you need)

**Comment by fujiapple852** [comment]
@unusualevent what you've said makes sense, and I don't have a good response.  What @c-git said is right, Trippy is simply a tool that can help you solve problem X by doing Y on the assumption that you know you can solve X with Y.  

There are many guides out there on how to correctly use traceroute tools, the one most often cited is [this](https://archive.nanog.org/sites/default/files/tuesday_steenbergen_troublshootingtraceroute_62.49.pdf) talk ([video](https://www.youtube.com/watch?v=WL0ZTcfSvB4)) which is quite old but covers the basics well.

For the more advanced use cases I would highly recommend reading the [Paris traceroute](https://paris-traceroute.net/about) introduction which outlines some of the limitations of classic traceroute and how they are overcome.  Then read about [Dublin traceroute](https://dublin-traceroute.net) which explains the limitations of the Paris approach and introduces solutions of its own.

I have always intended to write a longer form piece covering all of the above as a journey through why all of the various options for tracing exist.  I'll leave this issue open as a placeholder for writing such a thing, one day...

**Comment by fujiapple852** [comment]
@unusualevent I've written some basic notes on different ways to use Trippy:

https://github.com/fujiapple852/trippy?tab=readme-ov-file#what-are-the-recommended-settings-for-trippy

Let me know what you think.
