### ISSUE TITLE
Automatically fall back to IPv6 if host has no IPv4 addresses

### ISSUE THREAD

**Issue by artizirk** [fujiapple852/trippy#864]
Currently if you don't specify `-6` argument then trippy fails to resolve addresses for IPv6 only hosts and exits with an error. Default seems to be set IPv4. It would be great if it could use any address family available.

**Comment by artizirk** [comment]
Hi!

Flags `-4` and `-6` should still force `Ipv4Only` and `Ipv6Only` modes. Default without those arguments should be `trust-dns` `Ipv4thenIpv6` strategy.

I have created an PR #872 that implements this.

**Comment by fujiapple852** [comment]
Hi again @artizirk, thanks for the PR!

Thinking about this a bit more, some considerations below.

### Defaults and overrides

> Default without those arguments should be trust-dns `Ipv4thenIpv6` strategy

I was a bit uneasy about this at first, as it seems to express an option of favouring Ipv4 over Ipv6.  However...

Trippy currently supports both the `addr-family` config file entry and the `--ipv4` (`-4`) and `--ipv6` (`-6`) command line flags, all of which are optional.  The command line flags (which are mutually exclusive) take precedence over the config file entry and if neither are provided there is a default of Ipv4.  

Therefore Trippy is _already_ opinionated as it defaults to Ipv4.  

However, users are able to _change_ the default opinion in the config file (`addr-family`), and so we would need to provide the same capability here, by exposing all modes (`Ipv4Only`, `Ipv6Only`, `Ipv4thenIpv6` & `Ipv6thenIpv4`) in the config file for `addr-family` as well.

> Flags -4 and -6 should still force Ipv4Only and Ipv6Only modes.

Yes I think that is right.  The `--ipv4` (`-4`) and `--ipv6` (`-6`) can stay as shortcuts for `Ipv4Only` and `Ipv6Only` respectively, and continue to override whatever is set in the config file.

### System Resolver

The logic for the `system` resolver should match the logic for the other resolvers (`google`, `cloudflare` etc) which use `trust-dns`, which is an implementation detail users should not be aware of (fyi as great as it is, I'm looking to swap it for an non-async DNS resolver crate if I can).  This means we need to find a way to emulate the various modes provided by `trust-dns` in the `system` resolver.  

The `system` resolver will (depending on how the system is configured) returns both Ipv4 and Ipv6 results and so Trippy currently [filters](https://github.com/fujiapple852/trippy/blob/ee5fb8a06f619de0aff1ea8245315d648d8657b1/src/dns/lazy_resolver.rs#L214) the results based on the configured mode.

Therefore we would need to make this filtering smarter to respect the various "Fallback" options that `trust-dns` provides.  

Once we have that, it may make sense to _only_ use the `Ipv4AndIpv6` mode for `trust-dns`, and apply the logic after the call in a uniform way that is independent of the resolver used.

### Dns Resolve All 

Trippy 0.9.0 introduced the `dns-resolve-all` option where multiple ICMP traces will be started, one for each IP resolved for a given DNS entry.  Today this will be all Ipv4 or all Ipv6, never a mixture.  It would seems sensible that the same logic would apply, even when users specify the `Ipv4thenIpv6` or `Ipv6thenIpv4` config.  

If we wanted to support mixing (I'm not sure that I do...) then perhaps the `dns-resolve-all` flag should renamed to `dns-resolve-mode` and changed from a boolean to an enum where you can select something like `First`, `AllForFamily` or `All` where the latter mixes Ipv4 and Ipv6.

**Comment by fujiapple852** [comment]
@artizirk do you think you can your PR to cover the above?  Let me know if anything is unclear, happy to help guide you on chat (i'm fujiapple852 on both Matrix and Discord)

**Comment by fujiapple852** [comment]
@artizirk this turned out to be harder than I thought, WIP PR in #928.  

There is one outstanding issue with the logic to validate the `MultipathStrategy` which needs the Ipv4/Ipv6 mode as input, which is no longer known in advance given the fallback nature of `Ipv4thenIpv6` or `Ipv6thenIpv4`.  I need to work on this to find a way to validate this later in the process.

This PR adds a new `dns-resolve-family` (name is WIP) to the `[dns]` config section and the corresponding `--dns-resolve-family` command line flag.  The existing `addr-family` config file entry in the `[trippy]` section has been removed so this is a breaking change.  

This covers all resolvers (`system`, `google` etc)

**Comment by fujiapple852** [comment]
Regarding:

> There is one outstanding issue with the logic to validate the `MultipathStrategy` which needs the `Ipv4`/`Ipv6` mode as input, which is no longer known in advance given the fallback nature of `Ipv4thenIpv6` or `Ipv6thenIpv4`.

I solved this by adding logic to "downgrade" both Ipv4thenIpv6 and Ipv6thenIpv4 to be Ipv4Only if the user request the `MultipathStrategy::Dublin`.  This is a bit "magic", but it will at least be shown in the TUI header so users can see the downgraded mode.

**Comment by fujiapple852** [comment]
This feature is now merged in #928 and will be in the `0.10.0` release of Trippy.

**Comment by fujiapple852** [comment]
Support for IPv6/UDP/dublin was added (#272) in 0.10.0, and so the above "downgrade" logic is no lomnger required and may be removed. 

See #1476
