### ISSUE TITLE
[Feature Request] Improve the dot output

### ISSUE THREAD

**Issue by jmanteau** [fujiapple852/trippy#875]
Today, the dot output is quite basic and put only the IP in the node.
Ideally, it should have the reverse DNS added as well as the latency added on the edge (between nodes as well as cumulative).

The end vision should be to style as well the dot output to be able to achieve something closer to what mtraceroute does : [https://wiki.networksecuritytoolkit.org/nstwiki/index.php/HowTo_Use_The_Scapy:_Multi-Traceroute_-_MTR](https://wiki.networksecuritytoolkit.org/nstwiki/index.php/HowTo_Use_The_Scapy:_Multi-Traceroute_-_MTR)

**Comment by fujiapple852** [comment]
Hi @jmanteau,

Yes the initial version of the DOT report that ships with Trippy 0.9.0 is very basic.  I did start working on an enriched version (#797) but did not get it finished in time (see the screenshot of the WIP output).  

I like the idea of showing latency on the edges, that is nothing something I had considered.  Grouping nodes by AS was something I was thinking about adding, it looks nice in the example you linked to.  Is that example produced as a DOT file?  Do you have the DOT file for reference?

One thing that I think is needed here is the ability for users to specify parameters when invoking reports, for example to show either flows or latency on edges for the DOT report.  I think to do this these reports should become subcommand such that multiple per-subcommand flags could be added, so as a fictional example:

`trip dot --edge-value cumulative-latency -C 10 example.com`

Anyway I'll close this issue in favour of #797 as they are essentially duplicates and we can continue the conversation there.
