### ISSUE TITLE
Document meanings of status colours

### ISSUE THREAD

**Issue by tomviner** [fujiapple852/trippy#877]
I can see from https://github.com/fujiapple852/trippy/blob/a3e53bed5bc41e725e5417077885d770f6534c18/src/frontend/render/table.rs#L212-L219 the names of the conditions needed for each status colour.

The "is target" condition is explained here https://github.com/fujiapple852/trippy/blob/a3e53bed5bc41e725e5417077885d770f6534c18/src/backend/trace.rs#L47-L52

Would be nice to add a short section to the docs explaining these colours.

**Comment by fujiapple852** [comment]
@tomviner preview of the documentation for the columns, including the status column:

https://github.com/fujiapple852/trippy/tree/feat-jitter-config-file?tab=readme-ov-file#column-reference

WDYT?
