### ISSUE TITLE
[BREAKING CHANGE] Replace `mode` with sub-commands

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#880]
Replace the `mode` (`-m`) flag with sub-commands to allow specifying sub-command specific command line flags.

**Comment by c-git** [comment]
Humm if I may share an opinion on this. At first glace it doesn't appear to need to be a breaking change. Isn't it possible to support both (the -m without any args) and the subcommand with args?

**Comment by fujiapple852** [comment]
@c-git it would be possible, but perhaps not desirable.  

The motivation for introducing sub-commands is so that each sub-command can have bespoke arguments without polluting the common argument namespace.  

So for example, for the `dot` report we wish to add some arguments to dictate how it is rendered and these arguments would not make sense for other reports or for the Tui.  Likewise the various `--tui-xxx` arguments do not make sense when running in non-Tui modes but are allowed today.  This is essentially applying the classic "make invalid state unrepresentable" guidance applied to command line arguments.

If we were to preserve the current `--mode` argument it would, at best, be restricted to specify default arguments for the sub-command.

More generally, until Trippy hits 1.0 it should be considered unstable (technically going from `0.x` to `0.x+1` allows for breaking changes in the Cargo semver rules) such that we are not locked into non-optimal design choices prematurely.  

Therefore I'd prefer to deprecate (with a runtime warning) and include a prominent notice in the release note.

This may all be moot however, as we can only switch to use sub-commands if we can discover the magic incantations needed to allow `clap` to make positional arguments mandatory in sub-commands.

**Comment by c-git** [comment]
Yeah this makes sense. I think it's better to keep it clean.

**Comment by fujiapple852** [comment]
Putting this on the backlog for now, may revisit the idea in the future.
